automl:
  max_models: 20
  max_runtime_secs: 3600
  stopping_metric: "AUTO"
  algorithms:
    - "DRF"
    - "GLM"
    - "XGBoost"
    - "GBM"
    - "DeepLearning"
    - "StackedEnsemble"
  nfolds: 5
  seed: 1234
